export const posts = [
  {
    isActive: true,
    id: '1',
    post: 'Post 1',
    userId: '123421',
    username: 'Karthik',
    userPhotoId: '',
    postImageId: '',
    isAdmin: false,
    profession: 'President',
    createdDate: 'Today',
  },
  {
    isActive: true,
    id: '2',
    post: 'Post 2',
    userId: '12321',
    username: 'Talam',
    userPhotoId: '',
    postImageId: '',
    isAdmin: false,
    profession: 'Hero',
    createdDate: 'Today',
  },
  {
    isActive: true,
    id: '3',
    post: 'Post 3',
    userId: '1231',
    username: 'ABD',
    userPhotoId: '',
    postImageId: '',
    isAdmin: false,
    profession: 'Super Star',
    createdDate: 'Today',
  },
  {
    isActive: true,
    id: '4',
    post: 'Post 4',
    userId: '3421',
    username: 'Kohli',
    userPhotoId: '',
    postImageId: '',
    isAdmin: false,
    profession: 'Cap',
    createdDate: 'Today',
  },
  {
    isActive: true,
    id: '6',
    post: 'Post 6',
    userId: '121',
    username: 'Dhoni',
    userPhotoId: '',
    postImageId: '',
    isAdmin: false,
    profession: 'Thala',
    createdDate: 'Today',
  },
];
